name: teste_target_sistemas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  get_it: ^9.1.1
  mobx: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  mobx_codegen: ^2.7.4

flutter:
  uses-material-design: true
